/**
 * شجرة الحسابات الافتراضية للنظام الأم
 * حسب المواصفات في ملف 01_النظام_الأم.md
 */

export interface AccountSeed {
  code: string;
  name: string;
  nameEn: string;
  type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  nature: 'debit' | 'credit';
  isParent: boolean;
  parentCode?: string;
  systemAccount?: string;
}

export const defaultAccountsTree: AccountSeed[] = [
  // ==================== 1. الأصول ====================
  {
    code: '1',
    name: 'الأصول',
    nameEn: 'Assets',
    type: 'asset',
    nature: 'debit',
    isParent: true,
  },

  // 11 - الأصول المتداولة
  {
    code: '11',
    name: 'الأصول المتداولة',
    nameEn: 'Current Assets',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '1',
  },

  // 111 - النقدية والبنوك
  {
    code: '111',
    name: 'النقدية والبنوك',
    nameEn: 'Cash and Banks',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '11',
  },
  {
    code: '1111',
    name: 'الصندوق',
    nameEn: 'Cash',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '111',
    systemAccount: 'cash',
  },
  {
    code: '1112',
    name: 'البنوك',
    nameEn: 'Banks',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '111',
    systemAccount: 'bank',
  },

  // 112 - العملاء (للربط مع نظام الفوترة)
  {
    code: '112',
    name: 'العملاء',
    nameEn: 'Customers',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '11',
  },
  {
    code: '1121',
    name: 'ذمم العملاء',
    nameEn: 'Accounts Receivable',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '112',
    systemAccount: 'accounts_receivable',
  },

  // 113 - المخزون (للربط مع نظام المخزون)
  {
    code: '113',
    name: 'المخزون',
    nameEn: 'Inventory',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '11',
  },
  {
    code: '1131',
    name: 'مخزون عدادات',
    nameEn: 'Meters Inventory',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '113',
    systemAccount: 'inventory_meters',
  },
  {
    code: '1132',
    name: 'مخزون قواطع',
    nameEn: 'Breakers Inventory',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '113',
    systemAccount: 'inventory_breakers',
  },
  {
    code: '1133',
    name: 'مخزون أختام',
    nameEn: 'Seals Inventory',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '113',
    systemAccount: 'inventory_seals',
  },
  {
    code: '1134',
    name: 'مخزون شاشات STS',
    nameEn: 'STS Screens Inventory',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '113',
    systemAccount: 'inventory_sts',
  },

  // 114 - العهد والسلف
  {
    code: '114',
    name: 'العهد والسلف',
    nameEn: 'Advances and Custody',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '11',
  },
  {
    code: '1141',
    name: 'عهد الموظفين',
    nameEn: 'Employee Custody',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '114',
    systemAccount: 'employee_custody',
  },
  {
    code: '1142',
    name: 'سلف الموظفين',
    nameEn: 'Employee Advances',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '114',
    systemAccount: 'employee_advances',
  },

  // 115 - تأمينات لدى الغير
  {
    code: '115',
    name: 'تأمينات لدى الغير',
    nameEn: 'Deposits with Others',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '11',
  },

  // 12 - الأصول الثابتة
  {
    code: '12',
    name: 'الأصول الثابتة',
    nameEn: 'Fixed Assets',
    type: 'asset',
    nature: 'debit',
    isParent: true,
    parentCode: '1',
  },
  {
    code: '121',
    name: 'المولدات',
    nameEn: 'Generators',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_generators',
  },
  {
    code: '122',
    name: 'الألواح الشمسية',
    nameEn: 'Solar Panels',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_solar',
  },
  {
    code: '123',
    name: 'الكيابل والشبكات',
    nameEn: 'Cables and Networks',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_cables',
  },
  {
    code: '129',
    name: 'مجمع الإهلاك',
    nameEn: 'Accumulated Depreciation',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'accumulated_depreciation',
  },

  // ==================== 2. الخصوم ====================
  {
    code: '2',
    name: 'الخصوم',
    nameEn: 'Liabilities',
    type: 'liability',
    nature: 'credit',
    isParent: true,
  },

  // 21 - الخصوم المتداولة
  {
    code: '21',
    name: 'الخصوم المتداولة',
    nameEn: 'Current Liabilities',
    type: 'liability',
    nature: 'credit',
    isParent: true,
    parentCode: '2',
  },
  {
    code: '211',
    name: 'الموردين',
    nameEn: 'Suppliers',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '21',
    systemAccount: 'accounts_payable',
  },
  {
    code: '212',
    name: 'تأمينات من العملاء',
    nameEn: 'Customer Deposits',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '21',
    systemAccount: 'customer_deposits',
  },
  {
    code: '213',
    name: 'مستحقات الموظفين',
    nameEn: 'Employee Payables',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '21',
    systemAccount: 'employee_payables',
  },
  {
    code: '214',
    name: 'إيرادات مؤجلة',
    nameEn: 'Deferred Revenue',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '21',
    systemAccount: 'deferred_revenue',
  },

  // 22 - الحسابات الوسيطة (Clearing Accounts)
  {
    code: '22',
    name: 'الحسابات الوسيطة',
    nameEn: 'Clearing Accounts',
    type: 'liability',
    nature: 'credit',
    isParent: true,
    parentCode: '2',
  },
  {
    code: '221',
    name: 'وسيط صندوق التحصيل',
    nameEn: 'Collection Cash Box Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_cash_box',
  },
  {
    code: '222',
    name: 'وسيط بنك الحوشبي',
    nameEn: 'Al-Hawshabi Bank Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_bank_hawshabi',
  },
  {
    code: '223',
    name: 'وسيط إيرادات الفوترة',
    nameEn: 'Billing Revenue Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_revenue_billing',
  },
  {
    code: '224',
    name: 'وسيط إيرادات الدفع المسبق',
    nameEn: 'Prepaid Revenue Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_revenue_prepaid',
  },
  {
    code: '225',
    name: 'وسيط إيرادات صندوق الدعم',
    nameEn: 'Subsidy Fund Revenue Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_revenue_subsidy',
  },
  {
    code: '226',
    name: 'وسيط الموردين',
    nameEn: 'Suppliers Clearing',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '22',
    systemAccount: 'clearing_suppliers',
  },

  // 23 - الخصوم طويلة الأجل
  {
    code: '23',
    name: 'الخصوم طويلة الأجل',
    nameEn: 'Long-term Liabilities',
    type: 'liability',
    nature: 'credit',
    isParent: true,
    parentCode: '2',
  },
  {
    code: '231',
    name: 'قروض طويلة الأجل',
    nameEn: 'Long-term Loans',
    type: 'liability',
    nature: 'credit',
    isParent: false,
    parentCode: '23',
  },

  // ==================== 3. حقوق الملكية ====================
  {
    code: '3',
    name: 'حقوق الملكية',
    nameEn: 'Equity',
    type: 'equity',
    nature: 'credit',
    isParent: true,
  },
  {
    code: '31',
    name: 'رأس المال',
    nameEn: 'Capital',
    type: 'equity',
    nature: 'credit',
    isParent: false,
    parentCode: '3',
    systemAccount: 'capital',
  },
  {
    code: '32',
    name: 'حسابات الشركاء',
    nameEn: 'Partners Accounts',
    type: 'equity',
    nature: 'credit',
    isParent: false,
    parentCode: '3',
  },
  {
    code: '33',
    name: 'الأرباح المحتجزة',
    nameEn: 'Retained Earnings',
    type: 'equity',
    nature: 'credit',
    isParent: false,
    parentCode: '3',
    systemAccount: 'retained_earnings',
  },

  // ==================== 4. الإيرادات ====================
  {
    code: '4',
    name: 'الإيرادات',
    nameEn: 'Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: true,
  },

  // 41 - إيرادات الكهرباء
  {
    code: '41',
    name: 'إيرادات الكهرباء',
    nameEn: 'Electricity Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: true,
    parentCode: '4',
  },
  {
    code: '411',
    name: 'إيرادات كهرباء (عدادات تقليدية)',
    nameEn: 'Electricity Revenue (Traditional Meters)',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '41',
    systemAccount: 'revenue_electricity_traditional',
  },
  {
    code: '412',
    name: 'إيرادات كهرباء (دفع مسبق)',
    nameEn: 'Electricity Revenue (Prepaid)',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '41',
    systemAccount: 'revenue_electricity_prepaid',
  },
  {
    code: '413',
    name: 'إيرادات كهرباء (دعم حكومي)',
    nameEn: 'Electricity Revenue (Government Subsidy)',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '41',
    systemAccount: 'revenue_electricity_subsidy',
  },

  // 42 - إيرادات الخدمات
  {
    code: '42',
    name: 'إيرادات الخدمات',
    nameEn: 'Service Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: true,
    parentCode: '4',
  },
  {
    code: '421',
    name: 'إيرادات اشتراكات جديدة',
    nameEn: 'New Subscription Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '42',
    systemAccount: 'revenue_new_subscriptions',
  },
  {
    code: '422',
    name: 'إيرادات ترقية اشتراكات',
    nameEn: 'Subscription Upgrade Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '42',
    systemAccount: 'revenue_upgrades',
  },
  {
    code: '423',
    name: 'إيرادات بيع عدادات',
    nameEn: 'Meter Sales Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '42',
    systemAccount: 'revenue_meter_sales',
  },

  // 43 - إيرادات أخرى
  {
    code: '43',
    name: 'إيرادات أخرى',
    nameEn: 'Other Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '4',
    systemAccount: 'revenue_other',
  },

  // ==================== 5. المصروفات ====================
  {
    code: '5',
    name: 'المصروفات',
    nameEn: 'Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
  },

  // 51 - مصروفات التشغيل
  {
    code: '51',
    name: 'مصروفات التشغيل',
    nameEn: 'Operating Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '511',
    name: 'الوقود',
    nameEn: 'Fuel',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '51',
    systemAccount: 'expense_fuel',
  },
  {
    code: '512',
    name: 'الصيانة',
    nameEn: 'Maintenance',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '51',
    systemAccount: 'expense_maintenance',
  },
  {
    code: '513',
    name: 'قطع الغيار',
    nameEn: 'Spare Parts',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '51',
    systemAccount: 'expense_spare_parts',
  },

  // 52 - مصروفات إدارية
  {
    code: '52',
    name: 'مصروفات إدارية',
    nameEn: 'Administrative Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '521',
    name: 'إيجارات',
    nameEn: 'Rent',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '52',
  },
  {
    code: '522',
    name: 'مصروفات مكتبية',
    nameEn: 'Office Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '52',
  },

  // 53 - مصروفات الرواتب
  {
    code: '53',
    name: 'مصروفات الرواتب',
    nameEn: 'Salary Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '531',
    name: 'رواتب وأجور',
    nameEn: 'Salaries and Wages',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '53',
    systemAccount: 'expense_salaries',
  },
  {
    code: '532',
    name: 'بدلات',
    nameEn: 'Allowances',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '53',
    systemAccount: 'expense_allowances',
  },

  // 54 - الإهلاك
  {
    code: '54',
    name: 'الإهلاك',
    nameEn: 'Depreciation',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '5',
    systemAccount: 'expense_depreciation',
  },

  // 55 - تكلفة البضاعة المباعة
  {
    code: '55',
    name: 'تكلفة البضاعة المباعة',
    nameEn: 'Cost of Goods Sold',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '5',
    systemAccount: 'cogs',
  },

  // ==================== الحسابات الإضافية ====================

  // 124 - المباني والمنشآت
  {
    code: '124',
    name: 'المباني والمنشآت',
    nameEn: 'Buildings and Facilities',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_buildings',
  },

  // 125 - الأثاث والتجهيزات
  {
    code: '125',
    name: 'الأثاث والتجهيزات',
    nameEn: 'Furniture and Equipment',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_furniture',
  },

  // 126 - وسائل النقل
  {
    code: '126',
    name: 'وسائل النقل',
    nameEn: 'Vehicles',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_vehicles',
  },

  // 127 - أجهزة الحاسب الآلي
  {
    code: '127',
    name: 'أجهزة الحاسب الآلي',
    nameEn: 'Computer Equipment',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_computers',
  },

  // 128 - المحولات الكهربائية
  {
    code: '128',
    name: 'المحولات الكهربائية',
    nameEn: 'Electrical Transformers',
    type: 'asset',
    nature: 'debit',
    isParent: false,
    parentCode: '12',
    systemAccount: 'fixed_assets_transformers',
  },

  // 13 - مجمعات الإهلاك (تفصيلية)
  {
    code: '13',
    name: 'مجمعات الإهلاك',
    nameEn: 'Accumulated Depreciation',
    type: 'asset',
    nature: 'credit',
    isParent: true,
    parentCode: '1',
  },
  {
    code: '131',
    name: 'مجمع إهلاك المولدات',
    nameEn: 'Accumulated Depreciation - Generators',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_generators',
  },
  {
    code: '132',
    name: 'مجمع إهلاك الألواح الشمسية',
    nameEn: 'Accumulated Depreciation - Solar Panels',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_solar',
  },
  {
    code: '133',
    name: 'مجمع إهلاك الكيابل والشبكات',
    nameEn: 'Accumulated Depreciation - Cables',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_cables',
  },
  {
    code: '134',
    name: 'مجمع إهلاك المباني',
    nameEn: 'Accumulated Depreciation - Buildings',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_buildings',
  },
  {
    code: '135',
    name: 'مجمع إهلاك الأثاث',
    nameEn: 'Accumulated Depreciation - Furniture',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_furniture',
  },
  {
    code: '136',
    name: 'مجمع إهلاك وسائل النقل',
    nameEn: 'Accumulated Depreciation - Vehicles',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_vehicles',
  },
  {
    code: '137',
    name: 'مجمع إهلاك الحاسب الآلي',
    nameEn: 'Accumulated Depreciation - Computers',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_computers',
  },
  {
    code: '138',
    name: 'مجمع إهلاك المحولات',
    nameEn: 'Accumulated Depreciation - Transformers',
    type: 'asset',
    nature: 'credit',
    isParent: false,
    parentCode: '13',
    systemAccount: 'accum_depr_transformers',
  },

  // 44 - إيرادات الغرامات والتعويضات
  {
    code: '44',
    name: 'إيرادات الغرامات والتعويضات',
    nameEn: 'Fines and Compensation Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: true,
    parentCode: '4',
  },
  {
    code: '441',
    name: 'غرامات التأخير',
    nameEn: 'Late Payment Penalties',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '44',
    systemAccount: 'revenue_late_fees',
  },
  {
    code: '442',
    name: 'رسوم إعادة التوصيل',
    nameEn: 'Reconnection Fees',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '44',
    systemAccount: 'revenue_reconnection',
  },
  {
    code: '443',
    name: 'تعويضات سرقة الكهرباء',
    nameEn: 'Electricity Theft Compensation',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '44',
    systemAccount: 'revenue_theft_compensation',
  },

  // 45 - إيرادات استثمارية
  {
    code: '45',
    name: 'إيرادات استثمارية',
    nameEn: 'Investment Revenue',
    type: 'revenue',
    nature: 'credit',
    isParent: true,
    parentCode: '4',
  },
  {
    code: '451',
    name: 'فوائد بنكية',
    nameEn: 'Bank Interest',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '45',
    systemAccount: 'revenue_bank_interest',
  },
  {
    code: '452',
    name: 'أرباح استثمارات',
    nameEn: 'Investment Profits',
    type: 'revenue',
    nature: 'credit',
    isParent: false,
    parentCode: '45',
    systemAccount: 'revenue_investment_profits',
  },

  // 56 - مصروفات مالية
  {
    code: '56',
    name: 'مصروفات مالية',
    nameEn: 'Financial Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '561',
    name: 'فوائد قروض',
    nameEn: 'Loan Interest',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '56',
    systemAccount: 'expense_loan_interest',
  },
  {
    code: '562',
    name: 'عمولات بنكية',
    nameEn: 'Bank Charges',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '56',
    systemAccount: 'expense_bank_charges',
  },
  {
    code: '563',
    name: 'خسائر صرف العملات',
    nameEn: 'Foreign Exchange Losses',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '56',
    systemAccount: 'expense_forex_loss',
  },

  // 57 - مصروفات تسويقية
  {
    code: '57',
    name: 'مصروفات تسويقية',
    nameEn: 'Marketing Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '571',
    name: 'إعلانات ودعاية',
    nameEn: 'Advertising',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '57',
    systemAccount: 'expense_advertising',
  },
  {
    code: '572',
    name: 'علاقات عامة',
    nameEn: 'Public Relations',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '57',
    systemAccount: 'expense_pr',
  },

  // 58 - مصروفات متنوعة
  {
    code: '58',
    name: 'مصروفات متنوعة',
    nameEn: 'Miscellaneous Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '581',
    name: 'ضيافة واستقبال',
    nameEn: 'Hospitality',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_hospitality',
  },
  {
    code: '582',
    name: 'تبرعات وهبات',
    nameEn: 'Donations',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_donations',
  },
  {
    code: '583',
    name: 'مصروفات قانونية',
    nameEn: 'Legal Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_legal',
  },
  {
    code: '584',
    name: 'تأمينات',
    nameEn: 'Insurance',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_insurance',
  },
  {
    code: '585',
    name: 'اتصالات وإنترنت',
    nameEn: 'Communications and Internet',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_communications',
  },
  {
    code: '586',
    name: 'سفر وانتقالات',
    nameEn: 'Travel and Transportation',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_travel',
  },
  {
    code: '587',
    name: 'تدريب وتطوير',
    nameEn: 'Training and Development',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '58',
    systemAccount: 'expense_training',
  },

  // 59 - مصروفات الإهلاك التفصيلية
  {
    code: '59',
    name: 'مصروفات الإهلاك التفصيلية',
    nameEn: 'Detailed Depreciation Expenses',
    type: 'expense',
    nature: 'debit',
    isParent: true,
    parentCode: '5',
  },
  {
    code: '591',
    name: 'إهلاك المولدات',
    nameEn: 'Depreciation - Generators',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_generators',
  },
  {
    code: '592',
    name: 'إهلاك الألواح الشمسية',
    nameEn: 'Depreciation - Solar Panels',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_solar',
  },
  {
    code: '593',
    name: 'إهلاك الكيابل والشبكات',
    nameEn: 'Depreciation - Cables',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_cables',
  },
  {
    code: '594',
    name: 'إهلاك المباني',
    nameEn: 'Depreciation - Buildings',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_buildings',
  },
  {
    code: '595',
    name: 'إهلاك الأثاث',
    nameEn: 'Depreciation - Furniture',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_furniture',
  },
  {
    code: '596',
    name: 'إهلاك وسائل النقل',
    nameEn: 'Depreciation - Vehicles',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_vehicles',
  },
  {
    code: '597',
    name: 'إهلاك الحاسب الآلي',
    nameEn: 'Depreciation - Computers',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_computers',
  },
  {
    code: '598',
    name: 'إهلاك المحولات',
    nameEn: 'Depreciation - Transformers',
    type: 'expense',
    nature: 'debit',
    isParent: false,
    parentCode: '59',
    systemAccount: 'depr_expense_transformers',
  },
];
